// Generated by CoffeeScript 1.8.0
(function() {
  var Request, URL, clipboard, contextMenu, data, note, tabs;

  Request = require("sdk/request").Request;

  contextMenu = require("sdk/context-menu");

  note = require("sdk/notifications");

  clipboard = require("sdk/clipboard");

  tabs = require("sdk/tabs");

  URL = require("sdk/url");

  data = require("sdk/self").data;

  exports.main = function() {
    var cLink, iLink, pLink;
    cLink = contextMenu.Item({
      context: contextMenu.SelectorContext("a[href]"),
      label: "Akarin~ Shorten This Link",
      contentScriptFile: data.url("link.js"),
      onMessage: function(link) {
        var website;
        if (!URL.isValidURI(link)) {
          website = tabs.activeTab.url.split("/");
          link = "" + website[0] + website[1] + "//" + website[2] + link;
        }
        return Request({
          url: "http://api.waa.ai/shorten",
          content: {
            url: link
          },
          onComplete: function(response) {
            var json, sh;
            json = response.json;
            sh = json.data.url;
            sh = sh.replace(/\\\//g, "/");
            note.notify({
              title: "Waa.ai",
              text: sh,
              iconURL: data.url("icon.png")
            });
            return clipboard.set(sh);
          }
        }).post();
      }
    });
    pLink = contextMenu.Item({
      context: contextMenu.PageContext(),
      label: "Akarin~ Shorten This Page",
      contentScriptFile: data.url("current.js"),
      onMessage: function(page) {
        return Request({
          url: "http://api.waa.ai/shorten",
          content: {
            url: page
          },
          onComplete: function(response) {
            var json, sh;
            json = response.json;
            sh = json.data.url;
            sh = sh.replace(/\\\//g, "/");
            note.notify({
              title: "Waa.ai",
              text: sh,
              iconURL: data.url("icon.png")
            });
            return clipboard.set(sh);
          }
        }).post();
      }
    });
    return iLink = contextMenu.Item({
      context: contextMenu.SelectorContext("img"),
      label: "Akarin~ Shorten This Image",
      contentScriptFile: data.url("image.js"),
      onMessage: function(image) {
        return Request({
          url: "http://api.waa.ai/shorten",
          content: {
            url: image
          },
          onComplete: function(response) {
            var json, sh;
            json = response.json;
            sh = json.data.url;
            sh = sh.replace(/\\\//g, "/");
            note.notify({
              title: "Waa.ai",
              text: sh,
              iconURL: data.url("icon.png")
            });
            return clipboard.set(sh);
          }
        }).post();
      }
    });
  };

}).call(this);
